apiVersion: v1
kind: Service

metadata:
  name: cares-service

spec:
  type: NodePort

  selector:
    app: cares

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 30007